### ISSUE TITLE
Lots of 'EOF' messages after starting, but no data

### ISSUE THREAD

**Issue by MrHappy** [legolasbo/smartmeterBridge#1]
Was looking for something like this. I have a (very old) raspberry pi near my smartmeter which I currently use to get the data to emoncms.
Now I'm moving several things over to Home Assistant and this is one of the last thing to do.
The only package running (at all) is the arm-one.
I configured the config.yml and ran the program.
It returns a lot of lines with '2023/12/08 13:55:43 EOF'. (Whether debug is enabled or not.)
When I hit any key the ssh session stops and I have to login again.
I would like to get this to work.
Can you help me out?

**Comment by legolasbo** [comment]
Raspberrypi uses an ARM chipset, so it's no surprise that it can only execute the ARM version.

Can you share your config file and copy->paste the output generated when you run the program?

**Comment by MrHappy** [comment]
```
# serial_port is required and points to the serial file handle you want to use.
#serial_port: "/dev/ttyUSB0"
serial_port: "/dev/serial/by-id/usb-FTDI_P1_Converter_Cable_P13F11IL-if00-port0"

# dsmr_version is required to configure the serial port correctly.
# Must be one of:
# - "2"   - generic meter using DSMR version 2
# - "2.2" - Dutch meter using DSMR version 2.2
# - "3"   - generic meter using DSMR version 3
# - "Q3D" - Easymeter Q3D
# - "4"   - generic meter using DSMR version 4
# - "5"   - generic meter using DSMR version 5
# - "5B"  - Belgian meter using DSMR version 5
# - "5L"  - Luxembourg meter using DSMR version 5
# - "5S"  - Swedish meter using DSMR version 5
dsmr_version: "2.2"

# server is a map conta2.2ining the server config.
# - host configures the server address on which the server listens.
#   This can be a hostname, but this is not recommended because it will create a listener for at most one of the host's IP addresses.
#   If the parameter is left empty or a literal unspecified IP address, it will listen on all available unicast and anycast IP addresses of the local system.
# - port configures the port on which to listen. If the port is left empty or "0", a port number is automatically chosen.
server:
  host: ""
  port: 9988

# enable verbose mode to have the raw telegrams printed to stdOut
verbose: false

```

The console shows 2 lines that it started and listening, one line with the ipaddress of HA.
After that a lot of line with EOF, ending with
```
2023/12/08 14:45:19 EOF
2023/12/08 14:45:19 EOF
2023/12/08 14:45:19 EOF
2023/12/08 14:45:19 EOF
2023/12/08 14:45:19 EOF
2023/12/08 14:45:19 EOF
client_loop: send disconnect: Broken pipe
```
Occasionally it looks like there are other lines, but I was not able to catch them
